// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkYCZJAiaeqNGak60Bk0LNGMJgcy70eWI',
    appId: '1:169810590524:android:33a75a44644b471c96fc39',
    messagingSenderId: '169810590524',
    projectId: 'chrozik-e3e95',
    storageBucket: 'chrozik-e3e95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_KDXdNbpq3H2oCEbr0aEybp0lQzoE3M',
    appId: '1:169810590524:ios:8588f3eeb5cb4e2196fc39',
    messagingSenderId: '169810590524',
    projectId: 'chrozik-e3e95',
    storageBucket: 'chrozik-e3e95.appspot.com',
    androidClientId: '169810590524-eic1oeooftmnaav0bn4pdr9omkdhules.apps.googleusercontent.com',
    iosClientId: '169810590524-65c43fua9toknth57417ra5omv59vlg0.apps.googleusercontent.com',
    iosBundleId: 'com.chuong.chrozik.development',
  );
}
