name: chrozik
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1
environment:
   sdk: ">=2.18.5 <3.0.0"

dependencies:
   cupertino_icons: ^1.0.5
   firebase_core: ^2.3.0
   firebase_crashlytics: ^3.0.6
   flutter:
      sdk: flutter
   flutter_launcher_icons: ^0.11.0
   flutter_riverpod: ^2.1.1
   freezed_annotation: ^2.2.0
   json_annotation: ^4.7.0
   riverpod_annotation: ^1.0.6
   shared_preferences: ^2.0.15

dev_dependencies:
   build_runner: ^2.3.2
   flutter_flavorizr: ^2.1.5
   flutter_test:
      sdk: flutter
   freezed: ^2.2.1
   json_serializable: ^6.5.4
   riverpod_generator: ^1.0.6
   very_good_analysis: ^3.1.0

flutter:
   uses-material-design: true

   assets:
      - assets/images/

flavorizr:
   app:
      android:
         flavorDimensions: "default"

   flavors:
      develop:
         app:
            name: "Chrozik Develop"
         android:
            applicationId: "com.chuong.chrozik.develop"
            firebase:
               config: "android/app/firebase/google-services_dev.json"
         ios:
            bundleId: "com.chuong.chrozik.develop"
            firebase:
               config: "android/app/firebase/google-services_dev.json"

      release:
         app:
            name: "Chrozik"
         android:
            applicationId: "com.chuong.chrozik"
         ios:
            bundleId: "com.chuong.chrozik"
